// AUTO-GENERATED by scripts/sync-roofing-knowledge.mjs on 2026-07-01T11:14:24.689Z
// Source of truth: .lovable/knowledge/roofing-calculator.md
// Do NOT edit by hand — run `bun run sync:roofing` to regenerate.

import type { MaterialPrice } from "./screed-calc";

export interface RoofingKbMaterial {
  category: string; name: string; unit: string; price: number;
  rollM2?: number; purpose?: string; weightKgPerM2?: number; source?: string;
}
export interface RoofingKbWork {
  name: string; unit: string; basePrice: number;
  multiplierLogic: string; fixedMultiplier: number; source?: string;
}

/** Full material price book parsed from MD (5_Прайс_материалы). */
export const ROOFING_KB_MATERIALS: RoofingKbMaterial[] = [
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-СХ-2,0",
    "unit": "м²",
    "price": 96.9,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-СХ-2,5",
    "unit": "м²",
    "price": 104.52,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-ПЕ-2,5",
    "unit": "м²",
    "price": 124.2,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-СХ-3,5-П",
    "unit": "м²",
    "price": 112.08,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 3.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-СХ-4,0-П",
    "unit": "м²",
    "price": 120.66,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ЕКО-ПЕ-4,0-П",
    "unit": "м²",
    "price": 136.26,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ПЕ-2,5",
    "unit": "м²",
    "price": 142.14,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ПЕ-3,0",
    "unit": "м²",
    "price": 154.98,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 3,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "РУБЕРІТ",
    "name": "Руберіт ПЕ-4,0-ПС NEW",
    "unit": "м²",
    "price": 167.46,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕКО-ПЕ-2,5",
    "unit": "м²",
    "price": 146.46,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕКО-ПЕ-3,0",
    "unit": "м²",
    "price": 164.94,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 3,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕКО-ПЕ-4,0",
    "unit": "м²",
    "price": 204.84,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕКО-ПЕ-4,0-ПС",
    "unit": "м²",
    "price": 174.54,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол АПП-ПЕ-2,5",
    "unit": "м²",
    "price": 161.28,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 2.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол АПП-ПЕ-3,0",
    "unit": "м²",
    "price": 175.8,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 3,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол АПП-ПЕ-4,0-ПС",
    "unit": "м²",
    "price": 188.04,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол АПП-ПЕ-4,5-ПС",
    "unit": "м²",
    "price": 210,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол СБС-ПЕ-3,0",
    "unit": "м²",
    "price": 176.94,
    "rollM2": 15,
    "purpose": "Підкладковий",
    "weightKgPerM2": 3,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол СБС-ПЕ-4,0-ПС",
    "unit": "м²",
    "price": 190.02,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕЛАСТ-ПЕ-4,0",
    "unit": "м²",
    "price": 223.14,
    "rollM2": 10,
    "purpose": "Підкладковий",
    "weightKgPerM2": 4,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕЛАСТ-ПЕ-4,5-ПС",
    "unit": "м²",
    "price": 213.66,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 4.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ЕЛАСТ-ПЕ-5,0-ПС",
    "unit": "м²",
    "price": 239.82,
    "rollM2": 10,
    "purpose": "Верхній",
    "weightKgPerM2": 5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ФЛЕКС-ПЕ-4,1 (2,8мм)",
    "unit": "м²",
    "price": 240.66,
    "rollM2": 10,
    "purpose": "Підкладковий",
    "weightKgPerM2": 4.1,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ФЛЕКС-ПЕ-5,3-ПС (3,8мм)",
    "unit": "м²",
    "price": 261.6,
    "rollM2": 7.5,
    "purpose": "Верхній",
    "weightKgPerM2": 5.3,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "АКВАІЗОЛ",
    "name": "Акваізол ФЛЕКС-ПЕ-5,5-ПС (4,2мм)",
    "unit": "м²",
    "price": 312.54,
    "rollM2": 7.5,
    "purpose": "Верхній",
    "weightKgPerM2": 5.5,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Вентилятор покрівельний (флюгарка) d 75 мм",
    "unit": "шт",
    "price": 150,
    "rollM2": 1,
    "purpose": "Комплектуючі",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Вентилятор покрівельний (флюгарка) d 110 мм",
    "unit": "шт",
    "price": 234,
    "rollM2": 1,
    "purpose": "Комплектуючі",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Воронка покрівельна d 100 мм",
    "unit": "шт",
    "price": 162,
    "rollM2": 1,
    "purpose": "Комплектуючі",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Праймер бітумний АР-20 «Акваізол» (відро 17 кг/20 л)",
    "unit": "відро 20 л",
    "price": 1800,
    "rollM2": 20,
    "purpose": "Праймер",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Мастика бітумно-каучукова АМ-10 «Акваізол» (відро 10 кг)",
    "unit": "відро 10 кг",
    "price": 1050,
    "rollM2": 10,
    "purpose": "Мастика",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  },
  {
    "category": "Комплектуючі",
    "name": "Мастика бітумно-каучукова АМ-10 «Акваізол» (відро 3 кг)",
    "unit": "відро 3 кг",
    "price": 360,
    "rollM2": 3,
    "purpose": "Мастика",
    "weightKgPerM2": null,
    "source": "PDF Акваізол 30.03.2026, стр.1"
  }
];

/** Full work price book parsed from MD (6_Прайс_работы). */
export const ROOFING_KB_WORKS: RoofingKbWork[] = [
  {
    "name": "Подготовка поверхности",
    "unit": "м²",
    "basePrice": 20,
    "multiplierLogic": "1 раз",
    "fixedMultiplier": 1,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Нанесение праймера",
    "unit": "м²",
    "basePrice": 20,
    "multiplierLogic": "1 раз",
    "fixedMultiplier": 1,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Монтаж и обпайка воронки",
    "unit": "шт",
    "basePrice": 750,
    "multiplierLogic": "по слоям",
    "fixedMultiplier": 0,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Монтаж и обпайка аэратора",
    "unit": "шт",
    "basePrice": 550,
    "multiplierLogic": "по слоям",
    "fixedMultiplier": 0,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Монтаж рубероида по площади",
    "unit": "м²",
    "basePrice": 160,
    "multiplierLogic": "по слоям",
    "fixedMultiplier": 0,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Монтаж рубероида на примыканиях",
    "unit": "м.п.",
    "basePrice": 100,
    "multiplierLogic": "по слоям",
    "fixedMultiplier": 0,
    "source": "Фото прайса работ бригады"
  },
  {
    "name": "Галтели",
    "unit": "м.п.",
    "basePrice": 50,
    "multiplierLogic": "1 раз",
    "fixedMultiplier": 1,
    "source": "Пример листа замера"
  },
  {
    "name": "Расходники работ: рукавицы, валик, ножи и т.д.",
    "unit": "компл.",
    "basePrice": 1700,
    "multiplierLogic": "фикс.",
    "fixedMultiplier": 1,
    "source": "Пример листа замера"
  }
];

/** Raw coefficients pulled from MD 1_Ввод_замер (Расходные коэффициенты). */
export const ROOFING_KB_RAW_COEFFS = {
  "primerLPerM2": 0.5,
  "gasKgPerLayerM2": 0.4,
  "gasCylinderKg": 21,
  "gasPricePerKg": 45,
  "mastiKgPerNode": 0.5,
  "mastiZoneWidthM": 0.1,
  "overlapPercent": 0.12,
  "wastePercent": 0.05,
  "parapetHeightM": 0.3,
  "companyMarkup": 0.3,
  "fopRate": 0.06
} as const;

/** Overrides applied on top of DEFAULT_ROOFING_PRICES (buy = supplier price, sell = buy × 1.5). */
export const ROOFING_KB_PRICE_OVERRIDES: Record<string, MaterialPrice> = {
  "primer": {
    "buy": 90,
    "sell": 135
  },
  "opaika_mastic": {
    "buy": 105,
    "sell": 157.5
  },
  "funnel": {
    "buy": 162,
    "sell": 243
  },
  "aerator": {
    "buy": 150,
    "sell": 225
  },
  "gas": {
    "buy": 945,
    "sell": 1417.5
  }
};

/** Overrides applied on top of DEFAULT_ROOFING_WORKS. */
export const ROOFING_KB_WORK_OVERRIDES: Record<string, number> = {
  "primer_apply": 20,
  "funnel": 750,
  "aerator": 550,
  "rubemast_lay": 160,
  "parapet": 100,
  "galtel": 50
};

/** Overrides applied on top of DEFAULT_ROOFING_COEFFS. */
export const ROOFING_KB_COEFF_OVERRIDES = {
  "rubemastPrimerLPerM2": 0.5,
  "rubemastGasKgPerLayerM2": 0.4,
  "rubemastGasCylinderKg": 21,
  "rubemastOverlapCoef": 1.12,
  "parapetHeightCmDefault": 30,
  "fopRate": 0.06
} as const;

export const ROOFING_KB_META = {
  generatedAt: "2026-07-01T11:14:24.690Z",
  source: ".lovable/knowledge/roofing-calculator.md",
  materialsCount: 31,
  worksCount: 8,
};
