/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreedRouteImport } from './routes/screed'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsulationRouteImport } from './routes/insulation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DirectionsEditorRouteImport } from './routes/directions-editor'
import { Route as DemolitionRouteImport } from './routes/demolition'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ProductionIdRouteImport } from './routes/production.$id'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiPublicIntegrationsWorkerRouteImport } from './routes/api/public/integrations/worker'
import { Route as ApiPublicIntegrationsWebhookSlugRouteImport } from './routes/api/public/integrations/webhook.$slug'
import { Route as ApiPublicIntegrationsOauthCallbackRouteImport } from './routes/api/public/integrations/oauth.callback'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreedRoute = ScreedRouteImport.update({
  id: '/screed',
  path: '/screed',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsulationRoute = InsulationRouteImport.update({
  id: '/insulation',
  path: '/insulation',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsEditorRoute = DirectionsEditorRouteImport.update({
  id: '/directions-editor',
  path: '/directions-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DemolitionRoute = DemolitionRouteImport.update({
  id: '/demolition',
  path: '/demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIdRoute = ProductionIdRouteImport.update({
  id: '/production/$id',
  path: '/production/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsWorkerRoute =
  ApiPublicIntegrationsWorkerRouteImport.update({
    id: '/api/public/integrations/worker',
    path: '/api/public/integrations/worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsWebhookSlugRoute =
  ApiPublicIntegrationsWebhookSlugRouteImport.update({
    id: '/api/public/integrations/webhook/$slug',
    path: '/api/public/integrations/webhook/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsOauthCallbackRoute =
  ApiPublicIntegrationsOauthCallbackRouteImport.update({
    id: '/api/public/integrations/oauth/callback',
    path: '/api/public/integrations/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/objects/': typeof ObjectsIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/objects': typeof ObjectsIndexRoute
  '/production': typeof ProductionIndexRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/objects/': typeof ObjectsIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/history'
    | '/insulation'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/screed'
    | '/settings'
    | '/works'
    | '/invite/$token'
    | '/objects/$id'
    | '/objects/new'
    | '/production/$id'
    | '/objects/'
    | '/production/'
    | '/api/public/integrations/worker'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/history'
    | '/insulation'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/screed'
    | '/settings'
    | '/works'
    | '/invite/$token'
    | '/objects/$id'
    | '/objects/new'
    | '/production/$id'
    | '/objects'
    | '/production'
    | '/api/public/integrations/worker'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/history'
    | '/insulation'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/screed'
    | '/settings'
    | '/works'
    | '/invite/$token'
    | '/objects/$id'
    | '/objects/new'
    | '/production/$id'
    | '/objects/'
    | '/production/'
    | '/api/public/integrations/worker'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  BrandingRoute: typeof BrandingRoute
  ClientsRoute: typeof ClientsRoute
  DemolitionRoute: typeof DemolitionRoute
  DirectionsEditorRoute: typeof DirectionsEditorRoute
  EquipmentRoute: typeof EquipmentRoute
  HistoryRoute: typeof HistoryRoute
  InsulationRoute: typeof InsulationRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  MaterialsRoute: typeof MaterialsRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  RoofingRoute: typeof RoofingRoute
  ScreedRoute: typeof ScreedRoute
  SettingsRoute: typeof SettingsRoute
  WorksRoute: typeof WorksRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
  ProductionIdRoute: typeof ProductionIdRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  ApiPublicIntegrationsWorkerRoute: typeof ApiPublicIntegrationsWorkerRoute
  ApiPublicIntegrationsOauthCallbackRoute: typeof ApiPublicIntegrationsOauthCallbackRoute
  ApiPublicIntegrationsWebhookSlugRoute: typeof ApiPublicIntegrationsWebhookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screed': {
      id: '/screed'
      path: '/screed'
      fullPath: '/screed'
      preLoaderRoute: typeof ScreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insulation': {
      id: '/insulation'
      path: '/insulation'
      fullPath: '/insulation'
      preLoaderRoute: typeof InsulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions-editor': {
      id: '/directions-editor'
      path: '/directions-editor'
      fullPath: '/directions-editor'
      preLoaderRoute: typeof DirectionsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demolition': {
      id: '/demolition'
      path: '/demolition'
      fullPath: '/demolition'
      preLoaderRoute: typeof DemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/$id': {
      id: '/production/$id'
      path: '/production/$id'
      fullPath: '/production/$id'
      preLoaderRoute: typeof ProductionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/worker': {
      id: '/api/public/integrations/worker'
      path: '/api/public/integrations/worker'
      fullPath: '/api/public/integrations/worker'
      preLoaderRoute: typeof ApiPublicIntegrationsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/webhook/$slug': {
      id: '/api/public/integrations/webhook/$slug'
      path: '/api/public/integrations/webhook/$slug'
      fullPath: '/api/public/integrations/webhook/$slug'
      preLoaderRoute: typeof ApiPublicIntegrationsWebhookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/oauth/callback': {
      id: '/api/public/integrations/oauth/callback'
      path: '/api/public/integrations/oauth/callback'
      fullPath: '/api/public/integrations/oauth/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  BrandingRoute: BrandingRoute,
  ClientsRoute: ClientsRoute,
  DemolitionRoute: DemolitionRoute,
  DirectionsEditorRoute: DirectionsEditorRoute,
  EquipmentRoute: EquipmentRoute,
  HistoryRoute: HistoryRoute,
  InsulationRoute: InsulationRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  MaterialsRoute: MaterialsRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  RoofingRoute: RoofingRoute,
  ScreedRoute: ScreedRoute,
  SettingsRoute: SettingsRoute,
  WorksRoute: WorksRoute,
  InviteTokenRoute: InviteTokenRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  ObjectsNewRoute: ObjectsNewRoute,
  ProductionIdRoute: ProductionIdRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  ApiPublicIntegrationsWorkerRoute: ApiPublicIntegrationsWorkerRoute,
  ApiPublicIntegrationsOauthCallbackRoute:
    ApiPublicIntegrationsOauthCallbackRoute,
  ApiPublicIntegrationsWebhookSlugRoute: ApiPublicIntegrationsWebhookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
