/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DataAuditRouteImport } from './routes/data-audit'
import { Route as DataExchangeRouteImport } from './routes/data-exchange'
import { Route as DemolitionRouteImport } from './routes/demolition'
import { Route as DirectionsEditorRouteImport } from './routes/directions-editor'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InsulationRouteImport } from './routes/insulation'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as Roofing_pvcRouteImport } from './routes/roofing_pvc'
import { Route as Roofing_rubRouteImport } from './routes/roofing_rub'
import { Route as ScreedRouteImport } from './routes/screed'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as WorksRouteImport } from './routes/works'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmCallsRouteImport } from './routes/crm.calls'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmRequestsRouteImport } from './routes/crm.requests'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as MarketingAnalyticsRouteImport } from './routes/marketing.analytics'
import { Route as MarketingBudgetsRouteImport } from './routes/marketing.budgets'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing.campaigns'
import { Route as MarketingChannelsRouteImport } from './routes/marketing.channels'
import { Route as MarketingCreativesRouteImport } from './routes/marketing.creatives'
import { Route as MarketingFunnelsRouteImport } from './routes/marketing.funnels'
import { Route as MarketingIntegrationsRouteImport } from './routes/marketing.integrations'
import { Route as MarketingLandingRouteImport } from './routes/marketing.landing'
import { Route as MarketingLeadsRouteImport } from './routes/marketing.leads'
import { Route as MarketingRecommendationsRouteImport } from './routes/marketing.recommendations'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as ProductionIdRouteImport } from './routes/production.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicIntegrationsWorkerRouteImport } from './routes/api/public/integrations/worker'
import { Route as ApiPublicMarketingSyncRouteImport } from './routes/api/public/marketing/sync'
import { Route as ApiPublicIntegrationsBinotelCallCompletedRouteImport } from './routes/api/public/integrations/binotel/call-completed'
import { Route as ApiPublicIntegrationsBinotelCallSettingsRouteImport } from './routes/api/public/integrations/binotel/call-settings'
import { Route as ApiPublicIntegrationsOauthCallbackRouteImport } from './routes/api/public/integrations/oauth.callback'
import { Route as ApiPublicIntegrationsWebhookSlugRouteImport } from './routes/api/public/integrations/webhook.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAuditRoute = DataAuditRouteImport.update({
  id: '/data-audit',
  path: '/data-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExchangeRoute = DataExchangeRouteImport.update({
  id: '/data-exchange',
  path: '/data-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DemolitionRoute = DemolitionRouteImport.update({
  id: '/demolition',
  path: '/demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsEditorRoute = DirectionsEditorRouteImport.update({
  id: '/directions-editor',
  path: '/directions-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InsulationRoute = InsulationRouteImport.update({
  id: '/insulation',
  path: '/insulation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const Roofing_pvcRoute = Roofing_pvcRouteImport.update({
  id: '/roofing_pvc',
  path: '/roofing_pvc',
  getParentRoute: () => rootRouteImport,
} as any)
const Roofing_rubRoute = Roofing_rubRouteImport.update({
  id: '/roofing_rub',
  path: '/roofing_rub',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreedRoute = ScreedRouteImport.update({
  id: '/screed',
  path: '/screed',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCallsRoute = CrmCallsRouteImport.update({
  id: '/crm/calls',
  path: '/crm/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRequestsRoute = CrmRequestsRouteImport.update({
  id: '/crm/requests',
  path: '/crm/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/crm/tasks',
  path: '/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAnalyticsRoute = MarketingAnalyticsRouteImport.update({
  id: '/marketing/analytics',
  path: '/marketing/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBudgetsRoute = MarketingBudgetsRouteImport.update({
  id: '/marketing/budgets',
  path: '/marketing/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingChannelsRoute = MarketingChannelsRouteImport.update({
  id: '/marketing/channels',
  path: '/marketing/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCreativesRoute = MarketingCreativesRouteImport.update({
  id: '/marketing/creatives',
  path: '/marketing/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingFunnelsRoute = MarketingFunnelsRouteImport.update({
  id: '/marketing/funnels',
  path: '/marketing/funnels',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIntegrationsRoute = MarketingIntegrationsRouteImport.update({
  id: '/marketing/integrations',
  path: '/marketing/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingLandingRoute = MarketingLandingRouteImport.update({
  id: '/marketing/landing',
  path: '/marketing/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingLeadsRoute = MarketingLeadsRouteImport.update({
  id: '/marketing/leads',
  path: '/marketing/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRecommendationsRoute =
  MarketingRecommendationsRouteImport.update({
    id: '/marketing/recommendations',
    path: '/marketing/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIdRoute = ProductionIdRouteImport.update({
  id: '/production/$id',
  path: '/production/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsWorkerRoute =
  ApiPublicIntegrationsWorkerRouteImport.update({
    id: '/api/public/integrations/worker',
    path: '/api/public/integrations/worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMarketingSyncRoute = ApiPublicMarketingSyncRouteImport.update({
  id: '/api/public/marketing/sync',
  path: '/api/public/marketing/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsBinotelCallCompletedRoute =
  ApiPublicIntegrationsBinotelCallCompletedRouteImport.update({
    id: '/api/public/integrations/binotel/call-completed',
    path: '/api/public/integrations/binotel/call-completed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsBinotelCallSettingsRoute =
  ApiPublicIntegrationsBinotelCallSettingsRouteImport.update({
    id: '/api/public/integrations/binotel/call-settings',
    path: '/api/public/integrations/binotel/call-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsOauthCallbackRoute =
  ApiPublicIntegrationsOauthCallbackRouteImport.update({
    id: '/api/public/integrations/oauth/callback',
    path: '/api/public/integrations/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsWebhookSlugRoute =
  ApiPublicIntegrationsWebhookSlugRouteImport.update({
    id: '/api/public/integrations/webhook/$slug',
    path: '/api/public/integrations/webhook/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/data-audit': typeof DataAuditRoute
  '/data-exchange': typeof DataExchangeRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/roofing_pvc': typeof Roofing_pvcRoute
  '/roofing_rub': typeof Roofing_rubRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/warehouse': typeof WarehouseRoute
  '/works': typeof WorksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crm/calls': typeof CrmCallsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/requests': typeof CrmRequestsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/analytics': typeof MarketingAnalyticsRoute
  '/marketing/budgets': typeof MarketingBudgetsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/channels': typeof MarketingChannelsRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/funnels': typeof MarketingFunnelsRoute
  '/marketing/integrations': typeof MarketingIntegrationsRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/leads': typeof MarketingLeadsRoute
  '/marketing/recommendations': typeof MarketingRecommendationsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/crm/': typeof CrmIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/marketing/sync': typeof ApiPublicMarketingSyncRoute
  '/api/public/integrations/binotel/call-completed': typeof ApiPublicIntegrationsBinotelCallCompletedRoute
  '/api/public/integrations/binotel/call-settings': typeof ApiPublicIntegrationsBinotelCallSettingsRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/data-audit': typeof DataAuditRoute
  '/data-exchange': typeof DataExchangeRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/roofing_pvc': typeof Roofing_pvcRoute
  '/roofing_rub': typeof Roofing_rubRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/warehouse': typeof WarehouseRoute
  '/works': typeof WorksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crm/calls': typeof CrmCallsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/requests': typeof CrmRequestsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/analytics': typeof MarketingAnalyticsRoute
  '/marketing/budgets': typeof MarketingBudgetsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/channels': typeof MarketingChannelsRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/funnels': typeof MarketingFunnelsRoute
  '/marketing/integrations': typeof MarketingIntegrationsRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/leads': typeof MarketingLeadsRoute
  '/marketing/recommendations': typeof MarketingRecommendationsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/crm': typeof CrmIndexRoute
  '/marketing': typeof MarketingIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/production': typeof ProductionIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/marketing/sync': typeof ApiPublicMarketingSyncRoute
  '/api/public/integrations/binotel/call-completed': typeof ApiPublicIntegrationsBinotelCallCompletedRoute
  '/api/public/integrations/binotel/call-settings': typeof ApiPublicIntegrationsBinotelCallSettingsRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/data-audit': typeof DataAuditRoute
  '/data-exchange': typeof DataExchangeRoute
  '/demolition': typeof DemolitionRoute
  '/directions-editor': typeof DirectionsEditorRoute
  '/equipment': typeof EquipmentRoute
  '/finance': typeof FinanceRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/mcp': typeof McpRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/roofing_pvc': typeof Roofing_pvcRoute
  '/roofing_rub': typeof Roofing_rubRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/warehouse': typeof WarehouseRoute
  '/works': typeof WorksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/crm/calls': typeof CrmCallsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/requests': typeof CrmRequestsRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/analytics': typeof MarketingAnalyticsRoute
  '/marketing/budgets': typeof MarketingBudgetsRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/channels': typeof MarketingChannelsRoute
  '/marketing/creatives': typeof MarketingCreativesRoute
  '/marketing/funnels': typeof MarketingFunnelsRoute
  '/marketing/integrations': typeof MarketingIntegrationsRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/leads': typeof MarketingLeadsRoute
  '/marketing/recommendations': typeof MarketingRecommendationsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/production/$id': typeof ProductionIdRoute
  '/crm/': typeof CrmIndexRoute
  '/marketing/': typeof MarketingIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/integrations/worker': typeof ApiPublicIntegrationsWorkerRoute
  '/api/public/marketing/sync': typeof ApiPublicMarketingSyncRoute
  '/api/public/integrations/binotel/call-completed': typeof ApiPublicIntegrationsBinotelCallCompletedRoute
  '/api/public/integrations/binotel/call-settings': typeof ApiPublicIntegrationsBinotelCallSettingsRoute
  '/api/public/integrations/oauth/callback': typeof ApiPublicIntegrationsOauthCallbackRoute
  '/api/public/integrations/webhook/$slug': typeof ApiPublicIntegrationsWebhookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/data-audit'
    | '/data-exchange'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/finance'
    | '/history'
    | '/insulation'
    | '/integrations'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/mcp'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/roofing_pvc'
    | '/roofing_rub'
    | '/screed'
    | '/settings'
    | '/warehouse'
    | '/works'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crm/calls'
    | '/crm/contacts'
    | '/crm/leads'
    | '/crm/requests'
    | '/crm/tasks'
    | '/invite/$token'
    | '/marketing/analytics'
    | '/marketing/budgets'
    | '/marketing/campaigns'
    | '/marketing/channels'
    | '/marketing/creatives'
    | '/marketing/funnels'
    | '/marketing/integrations'
    | '/marketing/landing'
    | '/marketing/leads'
    | '/marketing/recommendations'
    | '/objects/$id'
    | '/objects/new'
    | '/orders/$id'
    | '/orders/new'
    | '/production/$id'
    | '/crm/'
    | '/marketing/'
    | '/objects/'
    | '/orders/'
    | '/production/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/integrations/worker'
    | '/api/public/marketing/sync'
    | '/api/public/integrations/binotel/call-completed'
    | '/api/public/integrations/binotel/call-settings'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/data-audit'
    | '/data-exchange'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/finance'
    | '/history'
    | '/insulation'
    | '/integrations'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/mcp'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/roofing_pvc'
    | '/roofing_rub'
    | '/screed'
    | '/settings'
    | '/warehouse'
    | '/works'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crm/calls'
    | '/crm/contacts'
    | '/crm/leads'
    | '/crm/requests'
    | '/crm/tasks'
    | '/invite/$token'
    | '/marketing/analytics'
    | '/marketing/budgets'
    | '/marketing/campaigns'
    | '/marketing/channels'
    | '/marketing/creatives'
    | '/marketing/funnels'
    | '/marketing/integrations'
    | '/marketing/landing'
    | '/marketing/leads'
    | '/marketing/recommendations'
    | '/objects/$id'
    | '/objects/new'
    | '/orders/$id'
    | '/orders/new'
    | '/production/$id'
    | '/crm'
    | '/marketing'
    | '/objects'
    | '/orders'
    | '/production'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/integrations/worker'
    | '/api/public/marketing/sync'
    | '/api/public/integrations/binotel/call-completed'
    | '/api/public/integrations/binotel/call-settings'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/branding'
    | '/clients'
    | '/data-audit'
    | '/data-exchange'
    | '/demolition'
    | '/directions-editor'
    | '/equipment'
    | '/finance'
    | '/history'
    | '/insulation'
    | '/integrations'
    | '/login'
    | '/logistics'
    | '/materials'
    | '/mcp'
    | '/operations'
    | '/reports'
    | '/roofing'
    | '/roofing_pvc'
    | '/roofing_rub'
    | '/screed'
    | '/settings'
    | '/warehouse'
    | '/works'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/crm/calls'
    | '/crm/contacts'
    | '/crm/leads'
    | '/crm/requests'
    | '/crm/tasks'
    | '/invite/$token'
    | '/marketing/analytics'
    | '/marketing/budgets'
    | '/marketing/campaigns'
    | '/marketing/channels'
    | '/marketing/creatives'
    | '/marketing/funnels'
    | '/marketing/integrations'
    | '/marketing/landing'
    | '/marketing/leads'
    | '/marketing/recommendations'
    | '/objects/$id'
    | '/objects/new'
    | '/orders/$id'
    | '/orders/new'
    | '/production/$id'
    | '/crm/'
    | '/marketing/'
    | '/objects/'
    | '/orders/'
    | '/production/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/integrations/worker'
    | '/api/public/marketing/sync'
    | '/api/public/integrations/binotel/call-completed'
    | '/api/public/integrations/binotel/call-settings'
    | '/api/public/integrations/oauth/callback'
    | '/api/public/integrations/webhook/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  BrandingRoute: typeof BrandingRoute
  ClientsRoute: typeof ClientsRoute
  DataAuditRoute: typeof DataAuditRoute
  DataExchangeRoute: typeof DataExchangeRoute
  DemolitionRoute: typeof DemolitionRoute
  DirectionsEditorRoute: typeof DirectionsEditorRoute
  EquipmentRoute: typeof EquipmentRoute
  FinanceRoute: typeof FinanceRoute
  HistoryRoute: typeof HistoryRoute
  InsulationRoute: typeof InsulationRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  MaterialsRoute: typeof MaterialsRoute
  McpRoute: typeof McpRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  RoofingRoute: typeof RoofingRoute
  Roofing_pvcRoute: typeof Roofing_pvcRoute
  Roofing_rubRoute: typeof Roofing_rubRoute
  ScreedRoute: typeof ScreedRoute
  SettingsRoute: typeof SettingsRoute
  WarehouseRoute: typeof WarehouseRoute
  WorksRoute: typeof WorksRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CrmCallsRoute: typeof CrmCallsRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmRequestsRoute: typeof CrmRequestsRoute
  CrmTasksRoute: typeof CrmTasksRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MarketingAnalyticsRoute: typeof MarketingAnalyticsRoute
  MarketingBudgetsRoute: typeof MarketingBudgetsRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingChannelsRoute: typeof MarketingChannelsRoute
  MarketingCreativesRoute: typeof MarketingCreativesRoute
  MarketingFunnelsRoute: typeof MarketingFunnelsRoute
  MarketingIntegrationsRoute: typeof MarketingIntegrationsRoute
  MarketingLandingRoute: typeof MarketingLandingRoute
  MarketingLeadsRoute: typeof MarketingLeadsRoute
  MarketingRecommendationsRoute: typeof MarketingRecommendationsRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ProductionIdRoute: typeof ProductionIdRoute
  CrmIndexRoute: typeof CrmIndexRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicIntegrationsWorkerRoute: typeof ApiPublicIntegrationsWorkerRoute
  ApiPublicMarketingSyncRoute: typeof ApiPublicMarketingSyncRoute
  ApiPublicIntegrationsBinotelCallCompletedRoute: typeof ApiPublicIntegrationsBinotelCallCompletedRoute
  ApiPublicIntegrationsBinotelCallSettingsRoute: typeof ApiPublicIntegrationsBinotelCallSettingsRoute
  ApiPublicIntegrationsOauthCallbackRoute: typeof ApiPublicIntegrationsOauthCallbackRoute
  ApiPublicIntegrationsWebhookSlugRoute: typeof ApiPublicIntegrationsWebhookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-audit': {
      id: '/data-audit'
      path: '/data-audit'
      fullPath: '/data-audit'
      preLoaderRoute: typeof DataAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-exchange': {
      id: '/data-exchange'
      path: '/data-exchange'
      fullPath: '/data-exchange'
      preLoaderRoute: typeof DataExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demolition': {
      id: '/demolition'
      path: '/demolition'
      fullPath: '/demolition'
      preLoaderRoute: typeof DemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions-editor': {
      id: '/directions-editor'
      path: '/directions-editor'
      fullPath: '/directions-editor'
      preLoaderRoute: typeof DirectionsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insulation': {
      id: '/insulation'
      path: '/insulation'
      fullPath: '/insulation'
      preLoaderRoute: typeof InsulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing_pvc': {
      id: '/roofing_pvc'
      path: '/roofing_pvc'
      fullPath: '/roofing_pvc'
      preLoaderRoute: typeof Roofing_pvcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing_rub': {
      id: '/roofing_rub'
      path: '/roofing_rub'
      fullPath: '/roofing_rub'
      preLoaderRoute: typeof Roofing_rubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screed': {
      id: '/screed'
      path: '/screed'
      fullPath: '/screed'
      preLoaderRoute: typeof ScreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/calls': {
      id: '/crm/calls'
      path: '/crm/calls'
      fullPath: '/crm/calls'
      preLoaderRoute: typeof CrmCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/requests': {
      id: '/crm/requests'
      path: '/crm/requests'
      fullPath: '/crm/requests'
      preLoaderRoute: typeof CrmRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/crm/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/analytics': {
      id: '/marketing/analytics'
      path: '/marketing/analytics'
      fullPath: '/marketing/analytics'
      preLoaderRoute: typeof MarketingAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/budgets': {
      id: '/marketing/budgets'
      path: '/marketing/budgets'
      fullPath: '/marketing/budgets'
      preLoaderRoute: typeof MarketingBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns': {
      id: '/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/channels': {
      id: '/marketing/channels'
      path: '/marketing/channels'
      fullPath: '/marketing/channels'
      preLoaderRoute: typeof MarketingChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/creatives': {
      id: '/marketing/creatives'
      path: '/marketing/creatives'
      fullPath: '/marketing/creatives'
      preLoaderRoute: typeof MarketingCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/funnels': {
      id: '/marketing/funnels'
      path: '/marketing/funnels'
      fullPath: '/marketing/funnels'
      preLoaderRoute: typeof MarketingFunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/integrations': {
      id: '/marketing/integrations'
      path: '/marketing/integrations'
      fullPath: '/marketing/integrations'
      preLoaderRoute: typeof MarketingIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/landing': {
      id: '/marketing/landing'
      path: '/marketing/landing'
      fullPath: '/marketing/landing'
      preLoaderRoute: typeof MarketingLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/leads': {
      id: '/marketing/leads'
      path: '/marketing/leads'
      fullPath: '/marketing/leads'
      preLoaderRoute: typeof MarketingLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/recommendations': {
      id: '/marketing/recommendations'
      path: '/marketing/recommendations'
      fullPath: '/marketing/recommendations'
      preLoaderRoute: typeof MarketingRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/': {
      id: '/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/$id': {
      id: '/production/$id'
      path: '/production/$id'
      fullPath: '/production/$id'
      preLoaderRoute: typeof ProductionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/worker': {
      id: '/api/public/integrations/worker'
      path: '/api/public/integrations/worker'
      fullPath: '/api/public/integrations/worker'
      preLoaderRoute: typeof ApiPublicIntegrationsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketing/sync': {
      id: '/api/public/marketing/sync'
      path: '/api/public/marketing/sync'
      fullPath: '/api/public/marketing/sync'
      preLoaderRoute: typeof ApiPublicMarketingSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/binotel/call-completed': {
      id: '/api/public/integrations/binotel/call-completed'
      path: '/api/public/integrations/binotel/call-completed'
      fullPath: '/api/public/integrations/binotel/call-completed'
      preLoaderRoute: typeof ApiPublicIntegrationsBinotelCallCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/binotel/call-settings': {
      id: '/api/public/integrations/binotel/call-settings'
      path: '/api/public/integrations/binotel/call-settings'
      fullPath: '/api/public/integrations/binotel/call-settings'
      preLoaderRoute: typeof ApiPublicIntegrationsBinotelCallSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/oauth/callback': {
      id: '/api/public/integrations/oauth/callback'
      path: '/api/public/integrations/oauth/callback'
      fullPath: '/api/public/integrations/oauth/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/webhook/$slug': {
      id: '/api/public/integrations/webhook/$slug'
      path: '/api/public/integrations/webhook/$slug'
      fullPath: '/api/public/integrations/webhook/$slug'
      preLoaderRoute: typeof ApiPublicIntegrationsWebhookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  BrandingRoute: BrandingRoute,
  ClientsRoute: ClientsRoute,
  DataAuditRoute: DataAuditRoute,
  DataExchangeRoute: DataExchangeRoute,
  DemolitionRoute: DemolitionRoute,
  DirectionsEditorRoute: DirectionsEditorRoute,
  EquipmentRoute: EquipmentRoute,
  FinanceRoute: FinanceRoute,
  HistoryRoute: HistoryRoute,
  InsulationRoute: InsulationRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  MaterialsRoute: MaterialsRoute,
  McpRoute: McpRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  RoofingRoute: RoofingRoute,
  Roofing_pvcRoute: Roofing_pvcRoute,
  Roofing_rubRoute: Roofing_rubRoute,
  ScreedRoute: ScreedRoute,
  SettingsRoute: SettingsRoute,
  WarehouseRoute: WarehouseRoute,
  WorksRoute: WorksRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CrmCallsRoute: CrmCallsRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmRequestsRoute: CrmRequestsRoute,
  CrmTasksRoute: CrmTasksRoute,
  InviteTokenRoute: InviteTokenRoute,
  MarketingAnalyticsRoute: MarketingAnalyticsRoute,
  MarketingBudgetsRoute: MarketingBudgetsRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingChannelsRoute: MarketingChannelsRoute,
  MarketingCreativesRoute: MarketingCreativesRoute,
  MarketingFunnelsRoute: MarketingFunnelsRoute,
  MarketingIntegrationsRoute: MarketingIntegrationsRoute,
  MarketingLandingRoute: MarketingLandingRoute,
  MarketingLeadsRoute: MarketingLeadsRoute,
  MarketingRecommendationsRoute: MarketingRecommendationsRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  ObjectsNewRoute: ObjectsNewRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ProductionIdRoute: ProductionIdRoute,
  CrmIndexRoute: CrmIndexRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductionIndexRoute: ProductionIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicIntegrationsWorkerRoute: ApiPublicIntegrationsWorkerRoute,
  ApiPublicMarketingSyncRoute: ApiPublicMarketingSyncRoute,
  ApiPublicIntegrationsBinotelCallCompletedRoute:
    ApiPublicIntegrationsBinotelCallCompletedRoute,
  ApiPublicIntegrationsBinotelCallSettingsRoute:
    ApiPublicIntegrationsBinotelCallSettingsRoute,
  ApiPublicIntegrationsOauthCallbackRoute:
    ApiPublicIntegrationsOauthCallbackRoute,
  ApiPublicIntegrationsWebhookSlugRoute: ApiPublicIntegrationsWebhookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
