/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Auto-generated by TanStack Router (manually maintained for this template).

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreedRouteImport } from './routes/screed'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsulationRouteImport } from './routes/insulation'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DemolitionRouteImport } from './routes/demolition'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as IndexRouteImport } from './routes/index'

const make = (RI: any, id: string) => RI.update({ id, path: id, getParentRoute: () => rootRouteImport } as any)

const WorksRoute = make(WorksRouteImport, '/works')
const SettingsRoute = make(SettingsRouteImport, '/settings')
const ScreedRoute = make(ScreedRouteImport, '/screed')
const RoofingRoute = make(RoofingRouteImport, '/roofing')
const ReportsRoute = make(ReportsRouteImport, '/reports')
const MaterialsRoute = make(MaterialsRouteImport, '/materials')
const LogisticsRoute = make(LogisticsRouteImport, '/logistics')
const LoginRoute = make(LoginRouteImport, '/login')
const InsulationRoute = make(InsulationRouteImport, '/insulation')
const HistoryRoute = make(HistoryRouteImport, '/history')
const EquipmentRoute = make(EquipmentRouteImport, '/equipment')
const DemolitionRoute = make(DemolitionRouteImport, '/demolition')
const ClientsRoute = make(ClientsRouteImport, '/clients')
const BrandingRoute = make(BrandingRouteImport, '/branding')
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branding': typeof BrandingRoute
  '/clients': typeof ClientsRoute
  '/demolition': typeof DemolitionRoute
  '/equipment': typeof EquipmentRoute
  '/history': typeof HistoryRoute
  '/insulation': typeof InsulationRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/materials': typeof MaterialsRoute
  '/reports': typeof ReportsRoute
  '/roofing': typeof RoofingRoute
  '/screed': typeof ScreedRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById extends FileRoutesByFullPath { __root__: typeof rootRouteImport }
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByFullPath
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandingRoute: typeof BrandingRoute
  ClientsRoute: typeof ClientsRoute
  DemolitionRoute: typeof DemolitionRoute
  EquipmentRoute: typeof EquipmentRoute
  HistoryRoute: typeof HistoryRoute
  InsulationRoute: typeof InsulationRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  MaterialsRoute: typeof MaterialsRoute
  ReportsRoute: typeof ReportsRoute
  RoofingRoute: typeof RoofingRoute
  ScreedRoute: typeof ScreedRoute
  SettingsRoute: typeof SettingsRoute
  WorksRoute: typeof WorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': { id: '/works'; path: '/works'; fullPath: '/works'; preLoaderRoute: typeof WorksRouteImport; parentRoute: typeof rootRouteImport }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/screed': { id: '/screed'; path: '/screed'; fullPath: '/screed'; preLoaderRoute: typeof ScreedRouteImport; parentRoute: typeof rootRouteImport }
    '/roofing': { id: '/roofing'; path: '/roofing'; fullPath: '/roofing'; preLoaderRoute: typeof RoofingRouteImport; parentRoute: typeof rootRouteImport }
    '/reports': { id: '/reports'; path: '/reports'; fullPath: '/reports'; preLoaderRoute: typeof ReportsRouteImport; parentRoute: typeof rootRouteImport }
    '/materials': { id: '/materials'; path: '/materials'; fullPath: '/materials'; preLoaderRoute: typeof MaterialsRouteImport; parentRoute: typeof rootRouteImport }
    '/logistics': { id: '/logistics'; path: '/logistics'; fullPath: '/logistics'; preLoaderRoute: typeof LogisticsRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/insulation': { id: '/insulation'; path: '/insulation'; fullPath: '/insulation'; preLoaderRoute: typeof InsulationRouteImport; parentRoute: typeof rootRouteImport }
    '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport }
    '/equipment': { id: '/equipment'; path: '/equipment'; fullPath: '/equipment'; preLoaderRoute: typeof EquipmentRouteImport; parentRoute: typeof rootRouteImport }
    '/demolition': { id: '/demolition'; path: '/demolition'; fullPath: '/demolition'; preLoaderRoute: typeof DemolitionRouteImport; parentRoute: typeof rootRouteImport }
    '/clients': { id: '/clients'; path: '/clients'; fullPath: '/clients'; preLoaderRoute: typeof ClientsRouteImport; parentRoute: typeof rootRouteImport }
    '/branding': { id: '/branding'; path: '/branding'; fullPath: '/branding'; preLoaderRoute: typeof BrandingRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, BrandingRoute, ClientsRoute, DemolitionRoute, EquipmentRoute, HistoryRoute,
  InsulationRoute, LoginRoute, LogisticsRoute, MaterialsRoute, ReportsRoute, RoofingRoute,
  ScreedRoute, SettingsRoute, WorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
